# Events that trigger workflows

You can configure your workflows to run when specific activity on GitHub happens, at a scheduled time, or when an event outside of GitHub occurs.

## About events that trigger workflows

Workflow triggers are events that cause a workflow to run. For more information about how to use workflow triggers, see [Triggering a workflow](/en/actions/how-tos/write-workflows/choose-when-workflows-run/trigger-a-workflow).

Some events have multiple activity types. For these events, you can specify which activity types will trigger a workflow run. For more information about what each activity type means, see [Webhook events and payloads](/en/webhooks/webhook-events-and-payloads).

> \[!NOTE]
> Not all webhook events trigger workflows.

Like GitHub Actions workflows, agentic workflows can be triggered by repository events and schedules. For an example, see [Creating GitHub Agentic Workflows](/en/copilot/how-tos/github-agentic-workflows/creating-github-agentic-workflows).

## `branch_protection_rule`

| Webhook event payload                                                                       | Activity types                             | `GITHUB_SHA`                  | `GITHUB_REF`   |
| ------------------------------------------------------------------------------------------- | ------------------------------------------ | ----------------------------- | -------------- |
| [`branch_protection_rule`](/en/webhooks/webhook-events-and-payloads#branch_protection_rule) | - `created`<br/>- `edited`<br/>- `deleted` | Last commit on default branch | Default branch |

> \[!NOTE]
>
> * More than one activity type triggers this event. For information about each activity type, see [Webhook events and payloads](/en/webhooks/webhook-events-and-payloads#branch_protection_rule). By default, all activity types trigger workflows that run on this event. You can limit your workflow runs to specific activity types using the `types` keyword. For more information, see [Workflow syntax for GitHub Actions](/en/actions/reference/workflows-and-actions/workflow-syntax#onevent_nametypes).
> * This event will only trigger a workflow run if the workflow file exists on the default branch.

Runs your workflow when branch protection rules in the workflow repository are changed. For more information about branch protection rules, see [About protected branches](/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches). For information about the branch protection rule APIs, see [Branches](/en/graphql/reference/branches#object-branchprotectionrule) in the GraphQL API documentation or [REST API endpoints for branches and their settings](/en/rest/branches).

For example, you can run a workflow when a branch protection rule has been `created` or `deleted`:

```yaml
on:
  branch_protection_rule:
    types: [created, deleted]
```

## `check_run`

| Webhook event payload                                             | Activity types                                                             | `GITHUB_SHA`                  | `GITHUB_REF`   |
| ----------------------------------------------------------------- | -------------------------------------------------------------------------- | ----------------------------- | -------------- |
| [`check_run`](/en/webhooks/webhook-events-and-payloads#check_run) | - `created`<br/>- `rerequested`<br/>- `completed`<br/>- `requested_action` | Last commit on default branch | Default branch |

> \[!NOTE]
>
> * More than one activity type triggers this event. For information about each activity type, see [Webhook events and payloads](/en/webhooks/webhook-events-and-payloads#check_run). By default, all activity types trigger workflows that run on this event. You can limit your workflow runs to specific activity types using the `types` keyword. For more information, see [Workflow syntax for GitHub Actions](/en/actions/reference/workflows-and-actions/workflow-syntax#onevent_nametypes).
> * This event will only trigger a workflow run if the workflow file exists on the default branch.
> * To prevent recursive workflows, this event does not trigger workflows if the check run's check suite was created by GitHub Actions or if the check suite's head SHA is associated with GitHub Actions.

Runs your workflow when activity related to a check run occurs. A check run is an individual test that is part of a check suite. For information, see [Using the REST API to interact with checks](/en/rest/guides/using-the-rest-api-to-interact-with-checks). For information about the check run APIs, see [Checks](/en/graphql/reference/checks#object-checkrun) in the GraphQL API documentation or [REST API endpoints for check runs](/en/rest/checks/runs).

For example, you can run a workflow when a check run has been `rerequested` or `completed`.

```yaml
on:
  check_run:
    types: [rerequested, completed]
```

## `check_suite`

| Webhook event payload                                                 | Activity types | `GITHUB_SHA`                  | `GITHUB_REF`   |
| --------------------------------------------------------------------- | -------------- | ----------------------------- | -------------- |
| [`check_suite`](/en/webhooks/webhook-events-and-payloads#check_suite) | - `completed`  | Last commit on default branch | Default branch |

> \[!NOTE]
>
> * More than one activity type triggers this event. For information about each activity type, see [Webhook events and payloads](/en/webhooks/webhook-events-and-payloads#check_suite). Although only the `completed` activity type is supported, specifying the activity type will keep your workflow specific if more activity types are added in the future. By default, all activity types trigger workflows that run on this event. You can limit your workflow runs to specific activity types using the `types` keyword. For more information, see [Workflow syntax for GitHub Actions](/en/actions/reference/workflows-and-actions/workflow-syntax#onevent_nametypes).
> * This event will only trigger a workflow run if the workflow file exists on the default branch.
> * To prevent recursive workflows, this event does not trigger workflows if the check suite was created by GitHub Actions or if the check suite's head SHA is associated with GitHub Actions.

Runs your workflow when check suite activity occurs. A check suite is a collection of the check runs created for a specific commit. Check suites summarize the status and conclusion of the check runs that are in the suite. For information, see [Using the REST API to interact with checks](/en/rest/guides/using-the-rest-api-to-interact-with-checks). For information about the check suite APIs, see [Checks](/en/graphql/reference/checks#object-checksuite) in the GraphQL API documentation or [REST API endpoints for check suites](/en/rest/checks/suites).

For example, you can run a workflow when a check suite has been `completed`.

```yaml
on:
  check_suite:
    types: [completed]
```

## `create`

| Webhook event payload                                       | Activity types | `GITHUB_SHA`                             | `GITHUB_REF`          |
| ----------------------------------------------------------- | -------------- | ---------------------------------------- | --------------------- |
| [`create`](/en/webhooks/webhook-events-and-payloads#create) | Not applicable | Last commit on the created branch or tag | Branch or tag created |

> \[!NOTE]
> An event will not be created when you create more than three tags at once.

Runs your workflow when someone creates a Git reference (Git branch or tag) in the workflow's repository. For information about the APIs to create a Git reference, see [Git](/en/graphql/reference/git#mutation-createref) in the GraphQL API documentation or [REST API endpoints for Git references](/en/rest/git/refs#create-a-reference).

For example, you can run a workflow when the `create` event occurs.

```yaml
on:
  create
```

## `delete`

| Webhook event payload                                       | Activity types | `GITHUB_SHA`                  | `GITHUB_REF`   |
| ----------------------------------------------------------- | -------------- | ----------------------------- | -------------- |
| [`delete`](/en/webhooks/webhook-events-and-payloads#delete) | Not applicable | Last commit on default branch | Default branch |

> \[!NOTE]
>
> * This event will only trigger a workflow run if the workflow file exists on the default branch.
> * An event will not be created when you delete more than three tags at once.

Runs your workflow when someone deletes a Git reference (Git branch or tag) in the workflow's repository. For information about the APIs to delete a Git reference, see [Git](/en/graphql/reference/git#mutation-deleteref) in the GraphQL API documentation or [REST API endpoints for Git references](/en/rest/git/refs#delete-a-reference).

For example, you can run a workflow when the `delete` event occurs.

```yaml
on:
  delete
```

## `deployment`

| Webhook event payload                                               | Activity types | `GITHUB_SHA`          | `GITHUB_REF`                                                      |
| ------------------------------------------------------------------- | -------------- | --------------------- | ----------------------------------------------------------------- |
| [`deployment`](/en/webhooks/webhook-events-and-payloads#deployment) | Not applicable | Commit to be deployed | Branch or tag to be deployed (empty if created with a commit SHA) |

Runs your workflow when someone creates a deployment in the workflow's repository. Deployments created with a commit SHA may not have a Git ref. For information about the APIs to create a deployment, see [Deployments](/en/graphql/reference/deployments#mutation-createdeployment) in the GraphQL API documentation or [REST API endpoints for repositories](/en/rest/repos#deployments).

For example, you can run a workflow when the `deployment` event occurs.

```yaml
on:
  deployment
```

## `deployment_status`

| Webhook event payload                                                             | Activity types | `GITHUB_SHA`          | `GITHUB_REF`                                   |
| --------------------------------------------------------------------------------- | -------------- | --------------------- | ---------------------------------------------- |
| [`deployment_status`](/en/webhooks/webhook-events-and-payloads#deployment_status) | Not applicable | Commit to be deployed | Branch or tag to be deployed (empty if commit) |

> \[!NOTE]
> When a deployment status's state is set to `inactive`, a workflow run will not be triggered.

Runs your workflow when a third party provides a deployment status. Deployments created with a commit SHA may not have a Git ref. For information about the APIs to create a deployment status, see [Deployments](/en/graphql/reference/deployments#mutation-createdeploymentstatus) in the GraphQL API documentation or [REST API endpoints for deployments](/en/rest/deployments#create-a-deployment-status).

For example, you can run a workflow when the `deployment_status` event occurs.

```yaml
on:
  deployment_status
```

## `discussion`

| Webhook event payload                                               | Activity types                                                                                                                                                                                                                  | `GITHUB_SHA`                  | `GITHUB_REF`   |
| ------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------- | -------------- |
| [`discussion`](/en/webhooks/webhook-events-and-payloads#discussion) | - `created`<br/>- `edited`<br/>- `deleted`<br/>- `transferred`<br/>- `pinned`<br/>- `unpinned`<br/>- `labeled`<br/>- `unlabeled`<br/>- `locked`<br/>- `unlocked`<br/>- `category_changed`<br/> - `answered`<br/> - `unanswered` | Last commit on default branch | Default branch |

> \[!NOTE]
>
> * More than one activity type triggers this event. For information about each activity type, see [Webhook events and payloads](/en/webhooks/webhook-events-and-payloads#discussion). By default, all activity types trigger workflows that run on this event. You can limit your workflow runs to specific activity types using the `types` keyword. For more information, see [Workflow syntax for GitHub Actions](/en/actions/reference/workflows-and-actions/workflow-syntax#onevent_nametypes).
> * This event will only trigger a workflow run if the workflow file exists on the default branch.
> * Webhook events for GitHub Discussions are currently in public preview and subject to change.

Runs your workflow when a discussion in the workflow's repository is created or modified. For activity related to comments on a discussion, use the [`discussion_comment`](#discussion_comment) event. For more information about discussions, see [About discussions](/en/discussions/collaborating-with-your-community-using-discussions/about-discussions). For information about the GraphQL API, see [Discussions](/en/graphql/reference/discussions#object-discussion).

For example, you can run a workflow when a discussion has been `created`, `edited`, or `answered`.

```yaml
on:
  discussion:
    types: [created, edited, answered]
```

## `discussion_comment`

| Webhook event payload                                                               | Activity types                                  | `GITHUB_SHA`                  | `GITHUB_REF`   |
| ----------------------------------------------------------------------------------- | ----------------------------------------------- | ----------------------------- | -------------- |
| [`discussion_comment`](/en/webhooks/webhook-events-and-payloads#discussion_comment) | - `created`<br/>- `edited`<br/>- `deleted`<br/> | Last commit on default branch | Default branch |

> \[!NOTE]
>
> * More than one activity type triggers this event. For information about each activity type, see [Webhook events and payloads](/en/webhooks/webhook-events-and-payloads#discussion_comment). By default, all activity types trigger workflows that run on this event. You can limit your workflow runs to specific activity types using the `types` keyword. For more information, see [Workflow syntax for GitHub Actions](/en/actions/reference/workflows-and-actions/workflow-syntax#onevent_nametypes).
> * This event will only trigger a workflow run if the workflow file exists on the default branch.
> * Webhook events for GitHub Discussions are currently in public preview and subject to change.

Runs your workflow when a comment on a discussion in the workflow's repository is created or modified. For activity related to a discussion as opposed to comments on the discussion, use the [`discussion`](#discussion) event. For more information about discussions, see [About discussions](/en/discussions/collaborating-with-your-community-using-discussions/about-discussions). For information about the GraphQL API, see [Discussions](/en/graphql/reference/discussions#object-discussion).

For example, you can run a workflow when a discussion comment has been `created` or `deleted`.

```yaml
on:
  discussion_comment:
    types: [created, deleted]
```

## `fork`

| Webhook event payload                                   | Activity types | `GITHUB_SHA`                  | `GITHUB_REF`   |
| ------------------------------------------------------- | -------------- | ----------------------------- | -------------- |
| [`fork`](/en/webhooks/webhook-events-and-payloads#fork) | Not applicable | Last commit on default branch | Default branch |

> \[!NOTE]
> This event will only trigger a workflow run if the workflow file exists on the default branch.

Runs your workflow when someone forks a repository. For information about the REST API, see [REST API endpoints for forks](/en/rest/repos/forks#create-a-fork).

For example, you can run a workflow when the `fork` event occurs.

```yaml
on:
  fork
```

## `gollum`

| Webhook event payload                                       | Activity types | `GITHUB_SHA`                  | `GITHUB_REF`   |
| ----------------------------------------------------------- | -------------- | ----------------------------- | -------------- |
| [`gollum`](/en/webhooks/webhook-events-and-payloads#gollum) | Not applicable | Last commit on default branch | Default branch |

> \[!NOTE]
> This event will only trigger a workflow run if the workflow file exists on the default branch.

Runs your workflow when someone creates or updates a Wiki page. For more information, see [About wikis](/en/communities/documenting-your-project-with-wikis/about-wikis).

For example, you can run a workflow when the `gollum` event occurs.

```yaml
on:
  gollum
```

## `image_version`

| Webhook event payload | Activity types | `GITHUB_SHA`                  | `GITHUB_REF`   |
| --------------------- | -------------- | ----------------------------- | -------------- |
| Not applicable        | Not applicable | Last commit on default branch | Default branch |

Runs your workflow when a new version of a specified image becomes available for use. This event is typically triggered after a successful image version creation, allowing you to automate actions such as deployment or notifications in response to new image versions.

This event supports glob patterns for both image names and versions. The example below triggers when a new image version matches any of the specified name and version combinations. For example, `["MyNewImage", 1.0.0]`, `["MyNewImage", 2.53.0]`, `["MyOtherImage", 1.0.0]`, and `["MyOtherImage", 2.0.0]`.

```yaml
on:
  image_version:
    names:
    - "MyNewImage"
    - "MyOtherImage"
    versions:
    - 1.*
    - 2.*
```

## `issue_comment`

| Webhook event payload                                                     | Activity types                                  | `GITHUB_SHA`                  | `GITHUB_REF`   |
| ------------------------------------------------------------------------- | ----------------------------------------------- | ----------------------------- | -------------- |
| [`issue_comment`](/en/webhooks/webhook-events-and-payloads#issue_comment) | - `created`<br/>- `edited`<br/>- `deleted`<br/> | Last commit on default branch | Default branch |

> \[!NOTE]
>
> * More than one activity type triggers this event. For information about each activity type, see [Webhook events and payloads](/en/webhooks/webhook-events-and-payloads#issue_comment). By default, all activity types trigger workflows that run on this event. You can limit your workflow runs to specific activity types using the `types` keyword. For more information, see [Workflow syntax for GitHub Actions](/en/actions/reference/workflows-and-actions/workflow-syntax#onevent_nametypes).
> * This event will only trigger a workflow run if the workflow file exists on the default branch.

Runs your workflow when an issue or pull request comment is created, edited, or deleted. For information about the issue comment APIs, see [Issues](/en/graphql/reference/issues#object-issuecomment) in the GraphQL API documentation or [Webhook events and payloads](/en/webhooks/webhook-events-and-payloads#issue_comment) in the REST API documentation.

For example, you can run a workflow when an issue or pull request comment has been `created` or `deleted`.

```yaml
on:
  issue_comment:
    types: [created, deleted]
```

### `issue_comment` on issues only or pull requests only

The `issue_comment` event occurs for comments on both issues and pull requests. You can use the `github.event.issue.pull_request` property in a conditional 
